//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demopr30
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.Состав_жюри = new HashSet<Состав_жюри>();
        }
    
        public long id_мероприятия { get; set; }
        public long id_активности { get; set; }
        public System.DateTime Дата { get; set; }
        public long День { get; set; }
        public Nullable<long> id_города { get; set; }
    
        public virtual Активности Активности { get; set; }
        public virtual Города Города { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_жюри> Состав_жюри { get; set; }
    }
}
